// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260509130801_MergeGearIntoSingleGearItem")]
    partial class MergeGearIntoSingleGearItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GearItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Length")
                        .HasColumnType("integer");

                    b.Property<int?>("LentBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Model")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Sex")
                        .HasColumnType("integer");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ToughTag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GearItems");
                });

            modelBuilder.Entity("Domain.Entities.Logbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GearItemId")
                        .HasColumnType("integer");

                    b.Property<int>("LentBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Logbook");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CID"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("CID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
