// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260509110515_RemoveUserNavigationProperty")]
    partial class RemoveUserNavigationProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BelayDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentBy")
                        .HasColumnType("integer");

                    b.Property<int?>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Model")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ToughTag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BelayDevices");
                });

            modelBuilder.Entity("Domain.Entities.Carabiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentBy")
                        .HasColumnType("integer");

                    b.Property<int?>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Model")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ToughTag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Carabiners");
                });

            modelBuilder.Entity("Domain.Entities.Crashpad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentBy")
                        .HasColumnType("integer");

                    b.Property<int?>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Model")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ToughTag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Crashpads");
                });

            modelBuilder.Entity("Domain.Entities.Harness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentBy")
                        .HasColumnType("integer");

                    b.Property<int?>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Model")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Sex")
                        .HasColumnType("integer");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ToughTag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Harnesses");
                });

            modelBuilder.Entity("Domain.Entities.Helmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentBy")
                        .HasColumnType("integer");

                    b.Property<int?>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Model")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ToughTag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Helmets");
                });

            modelBuilder.Entity("Domain.Entities.Quickdraw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentBy")
                        .HasColumnType("integer");

                    b.Property<int?>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Model")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ToughTag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Quickdraws");
                });

            modelBuilder.Entity("Domain.Entities.Rope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Length")
                        .HasColumnType("integer");

                    b.Property<int?>("LentBy")
                        .HasColumnType("integer");

                    b.Property<int?>("LentTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Model")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ToughTag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ropes");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CID"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.HasKey("CID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
