// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260513201632_MoreFieldsToEntities")]
    partial class MoreFieldsToEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GearItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpectedReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GearCategory")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("InspectedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Length")
                        .HasColumnType("integer");

                    b.Property<int?>("LentByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentToUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Sex")
                        .HasColumnType("integer");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("integer");

                    b.Property<string>("ToughTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InspectedByUserId");

                    b.HasIndex("LentByUserId");

                    b.HasIndex("LentToUserId");

                    b.ToTable("GearItems");
                });

            modelBuilder.Entity("Domain.Entities.Logbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GearItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("InspectedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("LentByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LentToUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GearItemId");

                    b.HasIndex("InspectedByUserId");

                    b.HasIndex("LentByUserId");

                    b.HasIndex("LentToUserId");

                    b.ToTable("Logbook");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CID")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int?>("MemberType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.GearItem", b =>
                {
                    b.HasOne("Domain.Entities.User", "InspectedByUser")
                        .WithMany()
                        .HasForeignKey("InspectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "LentByUser")
                        .WithMany()
                        .HasForeignKey("LentByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "LentToUser")
                        .WithMany()
                        .HasForeignKey("LentToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InspectedByUser");

                    b.Navigation("LentByUser");

                    b.Navigation("LentToUser");
                });

            modelBuilder.Entity("Domain.Entities.Logbook", b =>
                {
                    b.HasOne("Domain.Entities.GearItem", "GearItem")
                        .WithMany()
                        .HasForeignKey("GearItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "InspectedByUser")
                        .WithMany()
                        .HasForeignKey("InspectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "LentByUser")
                        .WithMany()
                        .HasForeignKey("LentByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "LentToUser")
                        .WithMany()
                        .HasForeignKey("LentToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GearItem");

                    b.Navigation("InspectedByUser");

                    b.Navigation("LentByUser");

                    b.Navigation("LentToUser");
                });
#pragma warning restore 612, 618
        }
    }
}
